"""Small offline English/Persian localization helpers for the Telegram UI."""

from __future__ import annotations

from copy import deepcopy
import re
from typing import Any


LANGUAGE_MENU = {
    "inline_keyboard": [[
        {"text": "🇬🇧 English", "callback_data": "language:en"},
        {"text": "🇮🇷 فارسی", "callback_data": "language:fa"},
    ]]
}


BUTTON_FA = {
    "All series": "همه سریال‌ها",
    "Cancel": "لغو",
    "Cancel movie": "لغو فیلم",
    "Cancel unprocessed movie": "لغو فیلم پردازش‌نشده",
    "Cancel episode": "لغو قسمت",
    "Cancel download": "لغو دانلود",
    "Choose a bot category or send a video…": "یک دسته را انتخاب کنید یا ویدیو بفرستید…",
    "Clear selection": "پاک کردن انتخاب",
    "Confirm movie": "تأیید فیلم",
    "Copy /movie_import": "کپی /movie_import",
    "Copy /movie_undo_batch": "کپی /movie_undo_batch",
    "Current series": "سریال فعلی",
    "Enter movie mode": "ورود به حالت فیلم",
    "Enter name manually": "وارد کردن نام دستی",
    "Enter series details manually": "وارد کردن دستی اطلاعات سریال",
    "Fix episode metadata": "اصلاح نام متادیتای قسمت‌ها",
    "Latest movie job": "آخرین عملیات فیلم",
    "Choose movie library": "انتخاب کتابخانه فیلم",
    "Choose series library": "انتخاب کتابخانه سریال",
    "📺 Series tools": "📺 ابزار سریال‌ها",
    "🎬 Movie tools": "🎬 ابزار فیلم‌ها",
    "Movie mode": "حالت فیلم",
    "Movies": "فیلم‌ها",
    "Next ➡️": "بعدی ➡️",
    "One revision back": "یک نسخه به عقب",
    "One revision forward": "یک نسخه به جلو",
    "Recover current": "بازیابی پوشه فعلی",
    "Recover current folder": "بازیابی پوشه فعلی",
    "Rename sorted files": "تغییر نام فایل‌های مرتب‌شده",
    "Retry import": "تلاش دوباره برای انتقال",
    "Replace existing": "جایگزینی فایل موجود",
    "Search manually": "جستجوی دستی",
    "Search using filename": "جستجو با نام فایل",
    "Search with a different name": "جستجو با نام دیگر",
    "Series": "سریال‌ها",
    "Series mode": "حالت سریال",
    "Sort back": "بازگشت مرتب‌سازی",
    "Sort forward": "اجرای دوباره مرتب‌سازی",
    "Sort history": "تاریخچه مرتب‌سازی",
    "Sort latest": "مرتب‌سازی آخرین دانلود",
    "Sort new files": "مرتب‌سازی فایل‌های جدید",
    "Sorter status": "وضعیت مرتب‌ساز",
    "Undo latest batch": "بازگردانی آخرین دسته",
    "Undo latest movie": "بازگردانی آخرین فیلم",
    "Use current folder without AI": "استفاده از پوشه فعلی بدون AI",
    "↩️ Undo & Recovery": "↩️ بازگردانی و بازیابی",
    "↩️ Undo latest sort": "↩️ بازگردانی آخرین مرتب‌سازی",
    "⚙️ Bot": "⚙️ ربات",
    "⚡ Quick Menu": "⚡ منوی سریع",
    "⚡ Quick menu": "⚡ منوی سریع",
    "⛔ Cancel": "⛔ لغو",
    "✅ Confirm": "✅ تأیید",
    "✅ Confirm download": "✅ تأیید دانلود",
    "✏️ Set/rename folder": "✏️ تنظیم یا تغییر نام پوشه",
    "❌ Cancel": "❌ لغو",
    "❓ Command list": "❓ فهرست دستورها",
    "❓ Help": "❓ راهنما",
    "⬅️ Categories": "⬅️ دسته‌ها",
    "⬅️ Advanced": "⬅️ پیشرفته",
    "⬅️ Main menu": "⬅️ منوی اصلی",
    "⬅️ Previous": "⬅️ قبلی",
    "⬇️ Download": "⬇️ دانلود",
    "🆔 Chat ID": "🆔 شناسه چت",
    "🎛 Main menu": "🎛 منوی اصلی",
    "🎛 Open main menu": "🎛 باز کردن منوی اصلی",
    "🎞 Episodes": "🎞 قسمت‌ها",
    "🎬 Jellyfin": "🎬 Jellyfin",
    "📁 Current folder": "📁 پوشه فعلی",
    "📁 Folders": "📁 پوشه‌ها",
    "📊 Status": "📊 وضعیت",
    "📋 Copy /episodes": "📋 کپی /episodes",
    "📋 Copy /episodes NAME": "📋 کپی /episodes NAME",
    "📋 Copy /imdb_fix_current": "📋 کپی /imdb_fix_current",
    "📋 Copy /imdb_search": "📋 کپی /imdb_search",
    "📋 Copy /remove": "📋 کپی /remove",
    "📋 Copy /renamefolder": "📋 کپی /renamefolder",
    "📋 Copy /resolve": "📋 کپی /resolve",
    "📋 Copy /setfolder": "📋 کپی /setfolder",
    "📋 Copy /sort_folder": "📋 کپی /sort_folder",
    "📋 Copy /undo_sort_batch": "📋 کپی /undo_sort_batch",
    "📋 Copy /usefolder": "📋 کپی /usefolder",
    "📋 Queue": "📋 صف",
    "📖 How to use": "📖 روش استفاده",
    "📖 How to use (English / فارسی)": "📖 روش استفاده و انتخاب زبان",
    "📚 All series": "📚 همه سریال‌ها",
    "📥 Downloads": "📥 دانلودها",
    "📺 Episodes": "📺 قسمت‌ها",
    "🔄 Scan Jellyfin": "🔄 اسکن Jellyfin",
    "🔄 Scan library": "🔄 اسکن کتابخانه",
    "🔎 IMDb": "🔎 IMDb",
    "🔎 IMDb title search": "🔎 جستجوی نام در IMDb",
    "🔢 Undo by batch ID": "🔢 بازگردانی با Batch ID",
    "🗂 Command categories": "🗂 دسته‌بندی دستورها",
    "🗂 Pick existing": "🗂 انتخاب پوشه موجود",
    "🗂 Pick existing folder": "🗂 انتخاب پوشه موجود",
    "🗑 Clear queue": "🗑 پاک کردن صف",
    "🗑 Remove one item": "🗑 حذف یک مورد",
    "🟢 Connection status": "🟢 وضعیت اتصال",
    "🟢 Jellyfin Status": "🟢 وضعیت Jellyfin",
    "🧹 Sort current": "🧹 مرتب‌سازی پوشه فعلی",
    "🧹 Sort latest": "🧹 مرتب‌سازی آخرین دانلود",
    "🧹 Sorting": "🧹 مرتب‌سازی",
    "🗄 Choose media library": "🗄 انتخاب کتابخانه رسانه",
    "🗄 Choose Library": "🗄 انتخاب کتابخانه",
    "🧰 Advanced": "🧰 پیشرفته",
    "📺 Animation Series": "📺 سریال‌های انیمیشن",
    "🎬 Animation Movies": "🎬 فیلم‌های انیمیشن",
    "📺 Video Series": "📺 سریال‌های ویدیویی",
    "🎬 Video Movies": "🎬 فیلم‌های ویدیویی",
    "🌐 Language": "🌐 زبان",
}


# These are sentence fragments rather than individual English words, so paths,
# filenames, titles, command names, and technical exception details stay intact.
TEXT_FA = {
    "Language changed to Persian.": "زبان ربات به فارسی تغییر کرد.",
    "Language changed to English.": "زبان ربات به انگلیسی تغییر کرد.",
    "Choose your language:\nزبان خود را انتخاب کنید:": "زبان خود را انتخاب کنید:\nChoose your language:",
    "Choose the guide language:\nزبان راهنما را انتخاب کنید:": "زبان راهنما را انتخاب کنید:\nChoose the guide language:",
    "Persistent category keyboard enabled below the message box.": "صفحه‌کلید دائمی دسته‌بندی زیر کادر پیام فعال شد.",
    "Category keyboard enabled. Choose a category below, or keep using slash commands.": "صفحه‌کلید دسته‌بندی فعال شد. یک دسته را انتخاب کنید یا از دستورهای / استفاده کنید.",
    "Download and sorting control menu:": "منوی کنترل دانلود و مرتب‌سازی:",
    "Main control menu:": "منوی کنترل اصلی:",
    "Choose a command category:": "یک دسته دستور را انتخاب کنید:",
    "Advanced commands:": "دستورهای پیشرفته:",
    "Choose which movie library should receive new movies:": "کتابخانه مقصد فیلم‌های جدید را انتخاب کنید:",
    "Choose which series library should receive new episodes:": "کتابخانه مقصد قسمت‌های جدید را انتخاب کنید:",
    "Current library:": "کتابخانه فعلی:",
    "Library selected:": "کتابخانه انتخاب‌شده:",
    "Choose a destination. Selecting one also changes Series/Movie mode:": "یک مقصد را انتخاب کنید. این انتخاب حالت سریال/فیلم را هم تغییر می‌دهد:",
    "Choose or create a series folder before sending episodes.": "پیش از فرستادن قسمت‌ها، یک پوشه سریال انتخاب یا ایجاد کنید.",
    "Send movie files; each queued movie will remember this library.": "فایل‌های فیلم را بفرستید؛ هر فیلم صف‌شده این کتابخانه را به خاطر می‌سپارد.",
    "Unknown library. Use /libraries and choose a button.": "کتابخانه ناشناخته است. /libraries را بفرستید و یک دکمه را انتخاب کنید.",
    "Mode:": "حالت:",
    "Download commands:": "دستورهای دانلود:",
    "Folder commands:": "دستورهای پوشه:",
    "Sorting commands:": "دستورهای مرتب‌سازی:",
    "Undo and recovery commands:": "دستورهای بازگردانی و بازیابی:",
    "TV-series workflow:": "ابزار سریال‌ها:",
    "Independent movie workflow:": "ابزار مستقل فیلم:",
    "Jellyfin commands:": "دستورهای Jellyfin:",
    "IMDb fuzzy-search commands:": "دستورهای جستجوی تقریبی IMDb:",
    "Episode inventory commands:": "دستورهای فهرست قسمت‌ها:",
    "Bot information and help:": "اطلاعات و راهنمای ربات:",
    "To set a folder:\n/setfolder My Anime\n\nTo rename the current folder:\n/renamefolder Correct Anime Name\n\nThe buttons below copy editable command templates. Paste one, then add the name.": "برای تنظیم پوشه:\n/setfolder My Anime\n\nبرای تغییر نام پوشه فعلی:\n/renamefolder Correct Anime Name\n\nدکمه‌های زیر الگوهای قابل‌ویرایش دستورها را کپی می‌کنند. یکی را جای‌گذاری کنید و سپس نام را اضافه کنید.",
    "To undo a specific sorter batch:\n/undo_sort_batch BATCH_ID\n\nExample:\n/undo_sort_batch 20260628-024900-a1b2c3d4": "برای بازگردانی یک دسته مشخص مرتب‌سازی:\n/undo_sort_batch BATCH_ID\n\nمثال:\n/undo_sort_batch 20260628-024900-a1b2c3d4",
    "To find the official name and create a Jellyfin folder:\n/imdb_search dr ston\n\nTo search and safely rename the current folder:\n/imdb_fix_current\n\nYou can also provide a different search phrase:\n/imdb_fix_current dr ston": "برای پیدا کردن نام رسمی و ساخت پوشه Jellyfin:\n/imdb_search dr ston\n\nبرای جستجو و تغییر امن نام پوشه فعلی:\n/imdb_fix_current\n\nمی‌توانید عبارت جستجوی دیگری هم وارد کنید:\n/imdb_fix_current dr ston",
    "Unknown command. Send /help.": "دستور ناشناخته است. /help را ارسال کنید.",
    "Correct format:": "فرمت صحیح:",
    "Current target folder:": "پوشه مقصد فعلی:",
    "Target folder cleared.": "پوشه مقصد پاک شد.",
    "The queue is empty.": "صف خالی است.",
    "waiting for movie identification": "منتظر تشخیص فیلم",
    "no folder": "بدون پوشه",
    "more file(s)": "فایل دیگر",
    "Removed from the queue.": "از صف حذف شد.",
    "No removable item was found.": "مورد قابل حذفی پیدا نشد.",
    "Removed ": "حذف شد: ",
    " item(s) from the queue.": " مورد از صف.",
    "Queue (": "صف (",
    "Queue ID for commands:": "شناسه صف برای دستورها:",
    "Queue ID:": "شناسه صف:",
    "Current download-batch ID:": "شناسه دسته دانلود فعلی:",
    "Download ID": "شناسه دانلود",
    "Video added to the queue.": "ویدیو به صف اضافه شد.",
    "This video is already in the queue.": "این ویدیو از قبل در صف است.",
    "This video file is not supported and was not added to the queue.": "این فایل ویدیویی پشتیبانی نمی‌شود و به صف اضافه نشد.",
    "This file extension is not allowed in allowed_video_extensions.": "پسوند این فایل در allowed_video_extensions مجاز نیست.",
    "The file was not added to the queue:": "فایل به صف اضافه نشد:",
    "There are no ready files in the queue.": "فایل آماده‌ای در صف وجود ندارد.",
    "There are no ready files to download.": "فایل آماده‌ای برای دانلود وجود ندارد.",
    "Mistake in the list? Press Remove one item or send /remove, then reply with its number.": "مورد اشتباهی در فهرست است؟ حذف یک مورد یا /remove را بزنید و سپس شماره آن را بفرستید.",
    "Open /download first. It will show temporary numbers starting from 1 for the files in that review.": "ابتدا /download را باز کنید. فایل‌های همان بررسی با شماره‌های موقت از ۱ نمایش داده می‌شوند.",
    "Send the ID shown beside the movie or episode in the latest /download list.": "شناسه کنار فیلم یا قسمت در آخرین فهرست /download را بفرستید.",
    "Available IDs:": "شناسه‌های موجود:",
    "Available:": "موجود:",
    "Send /cancel to stop without removing anything.": "برای خروج بدون حذف چیزی /cancel را بفرستید.",
    "Send only a number from the latest /download list, or /cancel.": "فقط یک شماره از آخرین فهرست /download یا /cancel را بفرستید.",
    "That number is not in the latest /download list.": "این شماره در آخرین فهرست /download نیست.",
    "Send a number from": "شماره‌ای از",
    ", or /cancel.": " یا /cancel را بفرستید.",
    "That download review is no longer active. Open /download again.": "آن بررسی دانلود دیگر فعال نیست. /download را دوباره باز کنید.",
    "That item is no longer removable. Open /download again.": "آن مورد دیگر قابل حذف نیست. /download را دوباره باز کنید.",
    "Open /download again to review the updated list.": "برای بررسی فهرست به‌روز، /download را دوباره باز کنید.",
    "Remove operation cancelled. The download review was not changed.": "عملیات حذف لغو شد. بررسی دانلود تغییری نکرد.",
    "Removed #": "حذف شد #",
    "Download list continued:": "ادامه فهرست دانلود:",
    "There is no unconfirmed download request for this chat.": "درخواست دانلود تأییدنشده‌ای برای این چت وجود ندارد.",
    "These files do not have a target folder:": "این فایل‌ها پوشه مقصد ندارند:",
    "Final download destination:": "مقصد نهایی دانلود:",
    "Approx size:": "حجم تقریبی:",
    "Count:": "تعداد:",
    "Send /confirm_download to start, or /cancel.": "برای شروع /confirm_download و برای لغو /cancel را ارسال کنید.",
    "Download started.": "دانلود شروع شد.",
    "Download completed:": "دانلود کامل شد:",
    "Downloads finished.": "دانلودها پایان یافت.",
    "File already exists.": "فایل از قبل وجود دارد.",
    "already exists:": "از قبل وجود دارد:",
    "Send one of these:": "یکی از این دستورها را ارسال کنید:",
    "skipped; it already exists.": "رد شد؛ از قبل وجود دارد.",
    "No files were completed or imported. Fix the reported error, then use /download to retry.": "هیچ فایلی کامل یا منتقل نشد. خطای گزارش‌شده را رفع کنید و برای تلاش دوباره /download را بفرستید.",
    "Completed movies will now be imported automatically.": "فیلم‌های کامل‌شده اکنون به‌صورت خودکار منتقل می‌شوند.",
    "Some files did not complete; use /download to retry them.": "برخی فایل‌ها کامل نشدند؛ برای تلاش دوباره /download را بفرستید.",
    "Use /sort_latest to organize the latest downloaded series folder.": "برای مرتب‌سازی آخرین پوشه سریال دانلودشده از /sort_latest استفاده کنید.",
    "Download error for file": "خطای دانلود فایل",
    "Download timeout for file": "پایان مهلت دانلود فایل",
    "Telegram stopped sending data for": "تلگرام ارسال داده را متوقف کرد؛ مدت انتظار:",
    "Any incomplete .part file was kept; use /download to retry.": "هر فایل ناقص .part نگه داشته شد؛ برای تلاش دوباره /download را بفرستید.",
    "Operation cancelled.": "عملیات لغو شد.",
    "Cancel request registered.": "درخواست لغو ثبت شد.",
    "There is no active operation.": "عملیات فعالی وجود ندارد.",
    "Another download is already running.": "یک دانلود دیگر در حال اجراست.",
    "A download is already running.": "یک دانلود در حال اجراست.",
    "A download is already running for this chat.": "یک دانلود برای این چت در حال اجراست.",
    "The downloader is busy with another chat. Your queue was not changed.": "دانلودر مشغول کار برای چت دیگری است. صف شما تغییر نکرد.",
    "The downloader is busy. Your confirmation is still saved; try again shortly.": "دانلودر مشغول است. تأیید شما ذخیره مانده است؛ کمی بعد دوباره تلاش کنید.",
    "Wait for the current download to finish first.": "ابتدا منتظر پایان دانلود فعلی بمانید.",
    "Movie mode enabled.": "حالت فیلم فعال شد.",
    "Movie mode is disabled.": "حالت فیلم غیرفعال است.",
    "Movie mode is not configured.": "حالت فیلم تنظیم نشده است.",
    "Movie mode is not configured yet.": "حالت فیلم هنوز تنظیم نشده است.",
    "Series mode enabled.": "حالت سریال فعال شد.",
    "Send one movie video.": "یک ویدیوی فیلم ارسال کنید.",
    "Movie received but not downloaded yet.": "فیلم دریافت شد اما هنوز دانلود نشده است.",
    "Episode received but not downloaded yet.": "قسمت دریافت شد اما هنوز دانلود نشده است.",
    "AI identification started.": "تشخیص با هوش مصنوعی شروع شد.",
    "New series:": "سریال جدید:",
    "Is this name correct for the matching queued episodes?": "آیا این نام برای قسمت‌های مطابق در صف درست است؟",
    "Series confirmed:": "سریال تأیید شد:",
    "Use /download when finished sending.": "پس از پایان ارسال، /download را اجرا کنید.",
    "Next: /download": "مرحله بعد: /download",
    "Resolve the items above before downloading.": "پیش از دانلود، موارد بالا را مشخص کنید.",
    "Resolve the movie choices above before downloading.": "پیش از دانلود، انتخاب فیلم‌های بالا را مشخص کنید.",
    "Choose a different identity or cancel this movie.": "یک هویت دیگر انتخاب کنید یا این فیلم را لغو کنید.",
    "Movie ready:": "فیلم آماده است:",
    "was not queued:": "در صف قرار نگرفت:",
    "already in the library as": "از قبل در کتابخانه وجود دارد با نام",
    "the same movie is already pending as queue ID": "همین فیلم از قبل در صف است با شناسه",
    "the same movie is already pending for this library": "همین فیلم از قبل برای این کتابخانه در صف است",
    "the same movie is already included in this download batch": "همین فیلم از قبل در این دسته دانلود وجود دارد",
    "Staged failures remain safe. Use /movie_import ID after fixing them.": "فایل‌های ناموفق در staging امن می‌مانند. پس از رفع مشکل از /movie_import ID استفاده کنید.",
    "Use /movie_current to correct or cancel a held movie.": "برای اصلاح یا لغو فیلم نگه‌داشته‌شده از /movie_current استفاده کنید.",
    "Send the correct series title. The detected season and episode numbers will be kept for all matching files.": "نام صحیح سریال را ارسال کنید. شماره فصل و قسمت تشخیص‌داده‌شده برای همه فایل‌های مطابق حفظ می‌شود.",
    "Enter the series title, season, and episode manually.": "نام سریال، فصل و قسمت را به‌صورت دستی وارد کنید.",
    "No waiting episodes could use this series folder.": "هیچ قسمت منتظری نتوانست از این پوشه سریال استفاده کند.",
    "AI filename suggestion:": "پیشنهاد هوش مصنوعی برای نام فایل:",
    "AI identification is unavailable for movie": "تشخیص هوش مصنوعی برای فیلم در دسترس نیست",
    "AI identification is unavailable for episode": "تشخیص هوش مصنوعی برای قسمت در دسترس نیست",
    "AI needs more information for movie": "هوش مصنوعی برای فیلم به اطلاعات بیشتری نیاز دارد",
    "AI needs more information for episode": "هوش مصنوعی برای قسمت به اطلاعات بیشتری نیاز دارد",
    "Could not identify episode": "قسمت شناسایی نشد",
    "Choose manual details or use the current folder.": "اطلاعات دستی را انتخاب کنید یا از پوشه فعلی استفاده کنید.",
    "Series not found for episode": "سریال برای قسمت پیدا نشد",
    "Choose manual series details.": "اطلاعات دستی سریال را انتخاب کنید.",
    "Checking the existing IMDb title tool now...": "اکنون ابزار موجود IMDb بررسی می‌شود…",
    "Enter the series details in this format:": "اطلاعات سریال را با این قالب وارد کنید:",
    "Send the series details in this format:": "اطلاعات سریال را با این قالب ارسال کنید:",
    "Series Title | Season | Episode": "نام سریال | فصل | قسمت",
    "Series query:": "عبارت جستجوی سریال:",
    "Title query:": "عبارت جستجوی عنوان:",
    "Season:": "فصل:",
    "Episode:": "قسمت:",
    "Confidence:": "اطمینان:",
    "Library:": "کتابخانه:",
    "Detected:": "تشخیص‌داده‌شده:",
    "Safe incoming name:": "نام امن فایل ورودی:",
    "Episode identity confirmed.": "هویت قسمت تأیید شد.",
    "Episode queue item cancelled.": "قسمت از صف لغو شد.",
    "Episode could not be cancelled.": "قسمت قابل لغو نبود.",
    "This episode is no longer waiting for identification.": "این قسمت دیگر منتظر تشخیص نیست.",
    "This episode is no longer waiting for a folder.": "این قسمت دیگر منتظر انتخاب پوشه نیست.",
    "Use manual series details or the already selected current folder.": "از اطلاعات دستی سریال یا پوشه فعلی انتخاب‌شده استفاده کنید.",
    "Use filename search or enter the title manually.": "از جستجو با نام فایل یا ورود دستی عنوان استفاده کنید.",
    "How should I identify it?": "نام فیلم چگونه تشخیص داده شود؟",
    "Filename:": "نام فایل:",
    "Movie identity confirmed.": "مشخصات فیلم تأیید شد.",
    "Use /download to review the destination, then /confirm_download.": "برای بررسی مقصد /download و سپس برای شروع /confirm_download را بفرستید.",
    "Searching IMDb movies for:": "در حال جستجوی فیلم در IMDb برای:",
    "Choose the correct movie result.": "نتیجه صحیح فیلم را انتخاب کنید.",
    "Choose the correct movie result for this file:": "نتیجه صحیح فیلم را برای این فایل انتخاب کنید:",
    "This destination is already in use.": "این مقصد از قبل استفاده شده است.",
    "Incoming:": "فایل ورودی:",
    "Would be saved as:": "نام نهایی پیشنهادی:",
    "Existing Jellyfin file:": "فایل موجود در Jellyfin:",
    "Already queued as": "از قبل در صف است با شناسه",
    "Another file already uses this destination.": "فایل دیگری از قبل از این مقصد استفاده می‌کند.",
    "Replace archives the old media for rollback. If this is the wrong title, cancel and identify the file again.": "جایگزینی، فایل قدیمی را برای بازگردانی بایگانی می‌کند. اگر این نام اشتباه است، لغو کنید و فایل را دوباره شناسایی کنید.",
    "Replacement approved. The old library media will be backed up for rollback before the new file is installed.": "جایگزینی تأیید شد. پیش از نصب فایل جدید، رسانه قدیمی کتابخانه برای بازگردانی پشتیبان‌گیری می‌شود.",
    "Download cancelled for this file.": "دانلود این فایل لغو شد.",
    "It remains undownloaded so you can correct its identity or remove it from the queue.": "فایل دانلودنشده در صف می‌ماند تا هویت آن را اصلاح یا آن را از صف حذف کنید.",
    "Detected:": "تشخیص داده‌شده:",
    "The selected IMDb identity differs from the detected title/year.": "هویت انتخاب‌شده IMDb با نام یا سال تشخیص‌داده‌شده متفاوت است.",
    "The incoming filename contains year": "نام فایل ورودی شامل سال",
    "but the selected movie is": "اما سال فیلم انتخاب‌شده",
    "Source:": "منبع:",
    "Confirm this movie identity:": "مشخصات این فیلم را تأیید کنید:",
    "Title:": "عنوان:",
    "Year:": "سال:",
    "not specified": "مشخص نشده",
    "not available": "در دسترس نیست",
    "Folder:": "پوشه:",
    "File:": "فایل:",
    "Send the movie title, preferably with its year.": "نام فیلم را ترجیحاً همراه سال ارسال کنید.",
    "Send a different movie title, preferably with its year.": "نام دیگری برای فیلم، ترجیحاً همراه سال، ارسال کنید.",
    "The filename did not contain a useful movie title.": "نام فایل شامل عنوان قابل‌استفاده‌ای برای فیلم نبود.",
    "IMDb did not recognize the filename.": "IMDb نام فایل را تشخیص نداد.",
    "IMDb did not return a movie result.": "IMDb نتیجه‌ای برای فیلم برنگرداند.",
    "IMDb search is unavailable:": "جستجوی IMDb در دسترس نیست:",
    "This movie is already registered in the queue.": "این فیلم از قبل در صف ثبت شده است.",
    "This movie is no longer waiting for identification.": "این فیلم دیگر منتظر تشخیص نام نیست.",
    "This movie choice is no longer active.": "این انتخاب فیلم دیگر فعال نیست.",
    "This movie result expired.": "نتیجه جستجوی فیلم منقضی شد.",
    "This movie confirmation expired.": "مهلت تأیید فیلم تمام شد.",
    "This movie is no longer waiting for a name.": "این فیلم دیگر منتظر نام نیست.",
    "Movie queue item cancelled.": "مورد فیلم از صف لغو شد.",
    "Movie could not be cancelled.": "لغو فیلم ممکن نبود.",
    "Current movie job cancelled.": "عملیات فعلی فیلم لغو شد.",
    "The movie job could not be cancelled.": "لغو عملیات فیلم ممکن نبود.",
    "There is no removable current movie job.": "عملیات فیلم قابل‌حذفی وجود ندارد.",
    "No movie job exists yet.": "هنوز عملیات فیلمی وجود ندارد.",
    "Latest movie queue ID:": "شناسه آخرین فیلم در صف:",
    "Current mode:": "حالت فعلی:",
    "Movie:": "فیلم:",
    "Original file:": "فایل اصلی:",
    "waiting for identification": "منتظر تشخیص نام",
    "Checking movie import plan for queue ID": "در حال بررسی برنامه انتقال فیلم با شناسه صف",
    "Checking movie recovery job": "در حال بررسی عملیات بازیابی فیلم",
    "Movie import plan verified. Importing without overwriting:": "برنامه انتقال فیلم تأیید شد. انتقال بدون بازنویسی:",
    "Movie imported successfully.": "فیلم با موفقیت منتقل شد.",
    "Destination:": "مقصد:",
    "Batch ID:": "شناسه دسته:",
    "This movie job is closed; send another movie while remaining in movie mode.": "این عملیات فیلم بسته شد؛ در صورت باقی ماندن در حالت فیلم، فیلم بعدی را ارسال کنید.",
    "Movie download is safe in staging, but import failed for queue ID": "دانلود فیلم در staging امن است، اما انتقال برای شناسه صف ناموفق بود",
    "Movie download is safe in staging, but import failed for recovery job": "دانلود فیلم در staging امن است، اما انتقال برای عملیات بازیابی ناموفق بود",
    "Recovery job": "عملیات بازیابی",
    "Fix the problem and use /movie_import": "مشکل را رفع کنید و از /movie_import استفاده کنید",
    " to retry.": " را برای تلاش دوباره اجرا کنید.",
    "No downloaded movie is waiting for import.": "فیلم دانلودشده‌ای منتظر انتقال نیست.",
    "The staged movie file is missing:": "فایل فیلم در staging پیدا نشد:",
    "Movie undo started:": "بازگردانی فیلم شروع شد:",
    "latest movie batch": "آخرین دسته فیلم",
    "Movie undo completed.": "بازگردانی فیلم کامل شد.",
    "Movie undo was incomplete; conflicting files were skipped.": "بازگردانی فیلم ناقص بود؛ فایل‌های متعارض رد شدند.",
    "Restored:": "بازگردانده‌شده:",
    "Skipped:": "ردشده:",
    "Movie undo failed:": "بازگردانی فیلم ناموفق بود:",
    "Movies cannot be restored while a download is running.": "هنگام اجرای دانلود نمی‌توان فیلم‌ها را بازگرداند.",
    "This chat has no imported movie batch to undo.": "این چت دسته فیلم منتقل‌شده‌ای برای بازگردانی ندارد.",
    "That movie batch does not belong to this chat.": "آن دسته فیلم متعلق به این چت نیست.",
    "Status:": "وضعیت:",
    "Tracked background tasks:": "کارهای پس‌زمینه در حال پیگیری:",
    "Incomplete .part files:": "فایل‌های ناقص .part:",
    "No files have been registered yet.": "هنوز فایلی ثبت نشده است.",
    "Jellyfin accepted the scan request.": "Jellyfin درخواست اسکن را پذیرفت.",
    "I will notify you when the library scan finishes.": "پس از پایان اسکن کتابخانه به شما اطلاع می‌دهم.",
    "I will monitor it and notify you when it finishes.": "آن را پیگیری می‌کنم و پس از پایان به شما اطلاع می‌دهم.",
    "Jellyfin library scan completed": "اسکن کتابخانه Jellyfin کامل شد",
    "Jellyfin connection is not configured.": "اتصال Jellyfin تنظیم نشده است.",
    "Jellyfin connection is not ready yet.": "اتصال Jellyfin هنوز آماده نیست.",
    "Searching IMDb for:": "در حال جستجو در IMDb برای:",
    "Folder renamed:": "نام پوشه تغییر کرد:",
    "Folder rename failed:": "تغییر نام پوشه ناموفق بود:",
    "No current folder is selected.": "هیچ پوشه فعلی انتخاب نشده است.",
    "No current folder is selected. Use /folders or /setfolder first.": "هیچ پوشه فعلی انتخاب نشده است. ابتدا از /folders یا /setfolder استفاده کنید.",
    "No current folder is set. Use /setfolder first.": "پوشه فعلی تنظیم نشده است. ابتدا /setfolder را اجرا کنید.",
    "No target folder is set. Use /setfolder NAME": "پوشه مقصد تنظیم نشده است. از /setfolder NAME استفاده کنید.",
    "No existing series folders were found.": "پوشه سریال موجودی پیدا نشد.",
    "No series folders were found inside the Jellyfin library.": "هیچ پوشه سریالی در کتابخانه Jellyfin پیدا نشد.",
    "No completed download has been recorded yet.": "هنوز دانلود کامل‌شده‌ای ثبت نشده است.",
    "No folder was specified.": "نام پوشه مشخص نشده است.",
    "Use /episodes Anime Name": "از /episodes Anime Name استفاده کنید",
    "or select one first with /setfolder.": "یا ابتدا با /setfolder یک پوشه انتخاب کنید.",
    "Choose an existing folder": "یک پوشه موجود را انتخاب کنید",
    "Existing folder selected as the target for new episodes:": "پوشه موجود به‌عنوان مقصد قسمت‌های جدید انتخاب شد:",
    "Target folder set after confirmation:": "پوشه مقصد پس از تأیید تنظیم شد:",
    "New files added to the queue after this will go to this folder.": "فایل‌های جدیدی که پس از این وارد صف شوند به این پوشه می‌روند.",
    "Send /folders to see existing folders.": "برای دیدن پوشه‌های موجود /folders را ارسال کنید.",
    "Send /setfolder NAME first.": "ابتدا /setfolder NAME را ارسال کنید.",
    "Folder not found:": "پوشه پیدا نشد:",
    "This folder does not exist:": "این پوشه وجود ندارد:",
    "This folder choice is no longer valid.": "این انتخاب پوشه دیگر معتبر نیست.",
    "Folder change cancelled.": "تغییر پوشه لغو شد.",
    "Safely renaming the folder and updating rollback paths...": "در حال تغییر امن نام پوشه و به‌روزرسانی مسیرهای بازگردانی…",
    "The new name is the same as the current name.": "نام جدید با نام فعلی یکسان است.",
    "You cannot rename the folder while a download or sort is running.": "هنگام دانلود یا مرتب‌سازی نمی‌توان نام پوشه را تغییر داد.",
    "Rename was not done because the destination folder already exists:": "تغییر نام انجام نشد زیرا پوشه مقصد از قبل وجود دارد:",
    "Rename failed and the bot state was not changed.": "تغییر نام ناموفق بود و وضعیت ربات تغییر نکرد.",
    "queued target(s) and rollback paths too.": "مقصد صف و مسیرهای بازگردانی نیز به‌روزرسانی شدند.",
    "\nUpdated ": "\nبه‌روزرسانی شد: ",
    "Decision saved. Send /download to continue.": "تصمیم ذخیره شد. برای ادامه /download را بفرستید.",
    "This file is not waiting for an overwrite decision.": "این فایل منتظر تصمیم بازنویسی نیست.",
    "The ID must be a number.": "شناسه باید عدد باشد.",
    "Format: /resolve ID skip|overwrite|save_with_suffix": "فرمت: /resolve ID skip|overwrite|save_with_suffix",
    "Files cannot be restored while a download is running.": "هنگام اجرای دانلود نمی‌توان فایل‌ها را بازگرداند.",
    "Sorting started:": "مرتب‌سازی شروع شد:",
    "Sorting:": "در حال مرتب‌سازی:",
    "Sorting completed.": "مرتب‌سازی کامل شد.",
    "Sorting failed. Use /sort_status for the detailed output.": "مرتب‌سازی ناموفق بود. برای جزئیات از /sort_status استفاده کنید.",
    "Sorting completed successfully.": "مرتب‌سازی با موفقیت کامل شد.",
    "Sorting finished with errors.": "مرتب‌سازی با خطا پایان یافت.",
    "Sorter error:": "خطای مرتب‌ساز:",
    "The sorter has not run yet.": "مرتب‌ساز هنوز اجرا نشده است.",
    "This chat has no recorded sort batch to undo.": "این چت دسته مرتب‌سازی ثبت‌شده‌ای برای بازگردانی ندارد.",
    "That sort batch does not belong to this chat.": "آن دسته مرتب‌سازی متعلق به این چت نیست.",
    "Latest run": "آخرین اجرا",
    "Sort undo started:": "بازگردانی مرتب‌سازی شروع شد:",
    "Sort undo error:": "خطای بازگردانی مرتب‌سازی:",
    "Undo completed successfully.": "بازگردانی با موفقیت کامل شد.",
    "Undo was incomplete or had errors.": "بازگردانی ناقص بود یا خطا داشت.",
    "Completed.": "کامل شد.",
    "Could not complete the action.": "عملیات کامل نشد.",
    "Scanning library files...": "در حال بررسی فایل‌های کتابخانه…",
    "Sending Jellyfin library scan request...": "در حال ارسال درخواست اسکن کتابخانه Jellyfin…",
    "Jellyfin scan started…": "اسکن Jellyfin شروع شد…",
    "Jellyfin scan is running…": "اسکن Jellyfin در حال اجراست…",
    "Jellyfin scan is already running…": "اسکن Jellyfin از قبل در حال اجراست…",
    "✅ Jellyfin is ready.": "✅ Jellyfin آماده است.",
    "A Jellyfin library scan is already running.": "اسکن کتابخانه Jellyfin از قبل در حال اجراست.",
    "Jellyfin library scan is running": "اسکن کتابخانه Jellyfin در حال اجراست",
    "Jellyfin scan progress:": "پیشرفت اسکن Jellyfin:",
    "Live scan state:": "وضعیت زنده اسکن:",
    "Live progress:": "پیشرفت زنده:",
    "Last Jellyfin task result:": "نتیجه آخرین کار Jellyfin:",
    "Live scan state unavailable:": "وضعیت زنده اسکن در دسترس نیست:",
    "Latest scan request:": "آخرین درخواست اسکن:",
    "Scan result:": "نتیجه اسکن:",
    "Progress:": "پیشرفت:",
    "not reported": "گزارش نشده",
    "not recorded yet": "هنوز ثبت نشده",
    "not recorded": "ثبت نشده",
    "Jellyfin scan error:": "خطای اسکن Jellyfin:",
    "Jellyfin connection failed:": "اتصال Jellyfin ناموفق بود:",
    "Jellyfin connection is working.": "اتصال Jellyfin برقرار است.",
    "Server:": "سرور:",
    "Server: unknown": "سرور: نامشخص",
    "Version: unknown": "نسخه: نامشخص",
    "Batch ID: unknown": "شناسه دسته: نامشخص",
    "The latest library state is ready.": "آخرین وضعیت کتابخانه آماده است.",
    "Completed at:": "زمان پایان:",
    "Jellyfin stopped scanning, but it did not report a successful completion.": "اسکن Jellyfin متوقف شد اما پایان موفق گزارش نشد.",
    "The scan was not cancelled. Use /jellyfin_status to check it.": "اسکن لغو نشده است؛ برای بررسی از /jellyfin_status استفاده کنید.",
    "Check the Jellyfin dashboard or server logs.": "داشبورد Jellyfin یا گزارش‌های سرور را بررسی کنید.",
    "Jellyfin accepted the scan, but the bot stopped waiting before Jellyfin reported completion.": "Jellyfin اسکن را پذیرفت، اما ربات پیش از گزارش پایان اسکن از انتظار خارج شد.",
    "Result:": "نتیجه:",
    "Suggested folder name:": "نام پیشنهادی پوشه:",
    "Choose the correct IMDb result:": "نتیجه صحیح IMDb را انتخاب کنید:",
    "This IMDb result expired.": "نتیجه IMDb منقضی شده است.",
    "This confirmation expired.": "مهلت این تأیید تمام شده است.",
    "The selected folder changed after this IMDb search.": "پس از این جستجوی IMDb پوشه انتخاب‌شده تغییر کرده است.",
    "The folder used for this IMDb search no longer exists.": "پوشه استفاده‌شده برای این جستجوی IMDb دیگر وجود ندارد.",
    "Nothing was renamed.": "هیچ نامی تغییر نکرد.",
    "Your entered name will be offered as the fallback.": "نام واردشده شما به‌عنوان گزینه جایگزین پیشنهاد می‌شود.",
    "Do you confirm?": "آیا تأیید می‌کنید؟",
    "Final folder format: Title (Year) [imdbid-ID]": "قالب نهایی پوشه: Title (Year) [imdbid-ID]",
    "The manual name is not valid:": "نام دستی معتبر نیست:",
    "The manual name is not valid either:": "نام دستی نیز معتبر نیست:",
    "Send another title.": "عنوان دیگری ارسال کنید.",
    "This movie queue item was not found.": "این مورد فیلم در صف پیدا نشد.",
    "IMDb filename search is unavailable:": "جستجوی نام فایل در IMDb در دسترس نیست:",
    "Send the movie title manually.": "نام فیلم را به‌صورت دستی ارسال کنید.",
    "The bot will let you use that exact name if IMDb remains unavailable.": "اگر IMDb همچنان در دسترس نباشد، ربات اجازه می‌دهد همان نام را استفاده کنید.",
    "Movie library:": "کتابخانه فیلم:",
    "Action:": "عملیات:",
    "Started at:": "زمان شروع:",
    "Stopped at:": "زمان توقف:",
    "Time:": "زمان:",
    "Version:": "نسخه:",
    "Current folder:": "پوشه فعلی:",
    "chat_id for this chat:": "شناسه این چت:",
    "Select an existing series folder": "یک پوشه سریال موجود را انتخاب کنید",
    "New episode detected:": "قسمت جدید تشخیص داده شد:",
    "already exists in the library:": "از قبل در کتابخانه وجود دارد:",
    "is already queued": "از قبل در صف است",
    "no recognizable episodes were found.": "قسمت قابل‌شناسایی پیدا نشد.",
    "No recognizable episodes were found in the library.": "هیچ قسمت قابل‌شناسایی در کتابخانه پیدا نشد.",
    "Jellyfin library episode summary": "خلاصه قسمت‌های کتابخانه Jellyfin",
    "Total:": "مجموع:",
    "episode(s)": "قسمت",
    "Missing:": "گمشده:",
    "latest E": "آخرین E",
    "result shortened; use /episodes NAME for details": "نتیجه کوتاه شد؛ برای جزئیات از /episodes NAME استفاده کنید",
}


STATUS_FA = {
    "awaiting_identification": "منتظر تشخیص نام",
    "cancelled": "لغوشده",
    "completed": "کامل‌شده",
    "downloading": "در حال دانلود",
    "failed": "ناموفق",
    "imported": "منتقل‌شده",
    "movie_import_failed": "انتقال فیلم ناموفق",
    "movie_undo_partial": "بازگردانی ناقص فیلم",
    "movie_undone": "فیلم بازگردانده‌شده",
    "queued": "در صف",
    "skipped": "ردشده",
    "waiting_overwrite": "منتظر تصمیم بازنویسی",
}


def _translate_dynamic_text(text: str) -> str:
    """Translate count/status sentences without modifying names or paths."""
    text = re.sub(
        r"Identifying (\d+) episode\(s\)…",
        lambda match: f"در حال شناسایی {match.group(1)} قسمت…",
        text,
    )
    text = re.sub(
        r"Identifying (\d+) movie\(s\)…",
        lambda match: f"در حال شناسایی {match.group(1)} فیلم…",
        text,
    )
    text = re.sub(
        r"Checked (\d+) episode\(s\): (\d+) ready, (\d+) need attention\.",
        lambda match: (
            f"{match.group(1)} قسمت بررسی شد: {match.group(2)} آماده، "
            f"{match.group(3)} نیازمند بررسی."
        ),
        text,
    )
    text = re.sub(
        r"Checked (\d+) movie\(s\): (\d+) ready, (\d+) need attention\.",
        lambda match: (
            f"{match.group(1)} فیلم بررسی شد: {match.group(2)} آماده، "
            f"{match.group(3)} نیازمند بررسی."
        ),
        text,
    )
    text = re.sub(
        r"Ready to save (\d+) file\(s\) — ([^:]+):",
        lambda match: (
            f"{match.group(1)} فایل آماده ذخیره است — {match.group(2)}:"
        ),
        text,
    )
    text = re.sub(
        r"(\d+) episode\(s\) ready\.",
        lambda match: f"{match.group(1)} قسمت آماده است.",
        text,
    )
    text = re.sub(
        r"(\d+) movie\(s\) ready\.",
        lambda match: f"{match.group(1)} فیلم آماده است.",
        text,
    )
    text = re.sub(
        r"(\d+) movie\(s\) imported\.",
        lambda match: f"{match.group(1)} فیلم وارد کتابخانه شد.",
        text,
    )
    text = re.sub(
        r"Movie import finished: (\d+) imported, (\d+) need attention\.",
        lambda match: (
            f"ورود فیلم‌ها پایان یافت: {match.group(1)} وارد شد، "
            f"{match.group(2)} نیازمند بررسی."
        ),
        text,
    )
    text = re.sub(
        r"Held (\d+) movie download\(s\) before transfer:",
        lambda match: f"پیش از انتقال، {match.group(1)} دانلود فیلم نگه داشته شد:",
        text,
    )
    text = re.sub(
        r"Jellyfin scan is running \((\d+)%\)…",
        lambda match: f"اسکن Jellyfin در حال اجراست ({match.group(1)}٪)…",
        text,
    )
    text = re.sub(
        r"Downloads finished\. (\d+) of (\d+) file\(s\) completed\.",
        lambda match: (
            f"دانلودها پایان یافت. {match.group(1)} از {match.group(2)} فایل کامل شد."
        ),
        text,
    )
    text = re.sub(
        r"Queue \((\d+) file\(s\)\):",
        lambda match: f"صف ({match.group(1)} فایل):",
        text,
    )
    text = re.sub(
        r"^\.\.\. and (\d+) more file\(s\)$",
        lambda match: f"... و {match.group(1)} فایل دیگر",
        text,
        flags=re.MULTILINE,
    )
    text = re.sub(
        r"^Total: (\d+) episode\(s\)$",
        lambda match: f"مجموع: {match.group(1)} قسمت",
        text,
        flags=re.MULTILINE,
    )
    text = re.sub(
        r"(\d+) eps \(latest E(\d+)\)",
        lambda match: f"{match.group(1)} قسمت (آخرین E{match.group(2)})",
        text,
    )

    def queue_line(match: re.Match[str]) -> str:
        kind = "سریال" if match.group(1) == "Series" else "فیلم"
        status = STATUS_FA.get(match.group(5), match.group(5))
        download_id = (
            f"(شناسه دانلود #{match.group(4)}) " if match.group(4) else ""
        )
        return (
            f"{kind} · {match.group(2)} مورد {match.group(3)} "
            f"{download_id}[{status}] "
        )

    return re.sub(
        r"^(Series|Movie) · (.*) item (\d+) "
        r"(?:\(Download ID #(\d+)\) )?\[([^\]]+)\] ",
        queue_line,
        text,
        flags=re.MULTILINE,
    )


def language_code(value: str) -> str:
    return "fa" if value == "fa" else "en"


def translate_text(text: str, language: str) -> str:
    if language_code(language) != "fa":
        return text
    translated = _translate_dynamic_text(text)
    for english, persian in sorted(
        TEXT_FA.items(), key=lambda item: len(item[0]), reverse=True
    ):
        translated = translated.replace(english, persian)
    return translated


def translate_markup(markup: dict | None, language: str) -> dict | None:
    if markup is None or language_code(language) != "fa":
        return markup
    result: dict[str, Any] = deepcopy(markup)

    def visit(value: Any) -> None:
        if isinstance(value, dict):
            for key, child in value.items():
                if key in {"text", "input_field_placeholder"} and isinstance(
                    child, str
                ):
                    value[key] = BUTTON_FA.get(child, child)
                elif key != "copy_text":
                    visit(child)
        elif isinstance(value, list):
            for child in value:
                visit(child)

    visit(result)
    return result


def reply_category_action(text: str, actions: dict[str, str]) -> str | None:
    if text in actions:
        return actions[text]
    reverse = {BUTTON_FA.get(label, label): action for label, action in actions.items()}
    return reverse.get(text)
